# serverless.yml

service: serverless-authorisation

provider:
  name: aws
  runtime: nodejs10.10
  stage: dev
  region: us-east-1

functions:
  auth:
    handler: auth.auth
    cors: true
  authorisationFunc:
    handler: index.handler
    events:
      - http:
          path: /api/v1/test
          method: ANY
          authorizer: auth
#      - http: 'ANY {proxy+}'
#        path: /api/v1/wdwd
#        method: ANY
#        authorizer: auth
      - http:
          path: /{any+}
          method: ANY
          authorizer: auth

plugins:
  - serverless-offline

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'